name: update data.json

on:
  push:
    branches: 
      - master
  schedule:
    - cron: '56 21 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: npm install
        run:
          npm install
      - name: npm start
        run:
          node app.js
      - name: detect changed files Auto commit & push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automated Change
          commit_user_name: GitHub Actions
          commit_user_email: actions@github.com
          commit_author: Author <actions@github.com>
          push_options: '--force'
